// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGJLNPsUKPs3gP8HH8b3YjYiPeKExDCQY',
    appId: '1:633234134006:web:21989bae470cf3f758edd7',
    messagingSenderId: '633234134006',
    projectId: 'donggubatreal',
    authDomain: 'donggubatreal.firebaseapp.com',
    storageBucket: 'donggubatreal.appspot.com',
    measurementId: 'G-WMPCQQVZY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSyslI1dTBI8rZsq0FwnRyUORQej4RiA',
    appId: '1:633234134006:android:cecb1f986c44086358edd7',
    messagingSenderId: '633234134006',
    projectId: 'donggubatreal',
    storageBucket: 'donggubatreal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvYRlnpEFKmSiDkSFhUERz4-mm3oJBX0',
    appId: '1:633234134006:ios:b580e989a5f9211958edd7',
    messagingSenderId: '633234134006',
    projectId: 'donggubatreal',
    storageBucket: 'donggubatreal.appspot.com',
    iosBundleId: 'com.example.dongguBat',
  );
}
