// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB5ENogKuLBI1QvdnwTNG1Y0cR5hLmYzk',
    appId: '1:807502359011:web:f380ee2a8a2376f11ad8d6',
    messagingSenderId: '807502359011',
    projectId: 'donggubat-a0c1b',
    authDomain: 'donggubat-a0c1b.firebaseapp.com',
    databaseURL: 'https://donggubat-a0c1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donggubat-a0c1b.appspot.com',
    measurementId: 'G-FKNYGS4QG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5zNW2QvS4LeXf8P6GhtShrAzWMeeBOSg',
    appId: '1:807502359011:android:3d1f34b44daf06971ad8d6',
    messagingSenderId: '807502359011',
    projectId: 'donggubat-a0c1b',
    databaseURL: 'https://donggubat-a0c1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donggubat-a0c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQscEDZxBxQ0RlhAyrCAWgtfNys-DzoVQ',
    appId: '1:807502359011:ios:76451db9fab0c26a1ad8d6',
    messagingSenderId: '807502359011',
    projectId: 'donggubat-a0c1b',
    databaseURL: 'https://donggubat-a0c1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'donggubat-a0c1b.appspot.com',
    iosBundleId: 'com.example.dongguBat',
  );
}
